Ticket 1069 - mobile styling
wri/gfw-mapbuilder pull request #1073
Opened 2020-05-28 18:37 UTC by eyosef

This PR implements mobile styling to align the app with prod. Fixes #1069

2020-05-30 15:32 UTC, vaidotasp requested changes
<img width="302" alt="Screen Shot 2020-05-30 at 11 29 39 AM" src="https://user-images.githubusercontent.com/12076555/83332435-2be64b00-a269-11ea-97d4-11d443f52a33.png">
Can we somehow get rid of that second scroll whitespace? it is happening due to overflow scroll on the left panel.

2020-05-30 15:32 UTC, vaidotasp commented on src/css/mapWidgets.scss
> +    // bottom: 7rem;
let's get rid of those commented out lines?

2020-05-30 15:32 UTC, vaidotasp commented on src/css/mapWidgets.scss
> +    /* left: 19rem; */
same here

2020-06-01 13:30 UTC, eyosef commented
@vaidotasp I couldn't reproduce the `overflow` style bug you ID'd, but I moved my use of `overflow` in `.tabview-container` into a media query since it's only needed in that context. Let me know what you think!

2020-06-01 14:24 UTC, vaidotasp commented
looks good

2020-06-01 14:24 UTC, merged