Ticket 1157 - update translation configs
wri/gfw-mapbuilder pull request #1160
Opened 2020-10-02 19:56 UTC by eyosef

This PR integrates Armenian & Dutch translations. Fixes #1157 

What it accomplishes;
- updates translation configs to include armenian and dutch
- to avoid breaking the app, sets `am: {}` & `du: {}` key/values where needed. In those instances, properties are set to English w/a clarifying note.

What it doesn't accomplish;
- There are instances where content doesn't appear because the languages aren't configured in the country configs. Just flagging purely for testing purposes. Details can be found [here](https://github.com/wri/gfw-mapbuilder/issues/1157#issuecomment-702908626).
- I tested by interacting with all of the widgets, but there are quite a few workflows in mapbuilder so if I missed something feel free to let me know

Test build, https://alpha.blueraster.io/gfw-mapbuilder/1157/

2020-10-07 18:10 UTC, vaidotasp requested changes

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  du: [
this need to be changed to nl

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  am: [
change to hy

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  du: [
nl

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  am: [
hy

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  du: [
nl

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  am: [
hy

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  du: {
nl

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  am: {
hy

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  am: {
hy

2020-10-07 18:10 UTC, vaidotasp commented on src/js/components/gfwContent/staticOptions.tsx
> +  du: {
nl

2020-10-07 18:18 UTC, eyosef commented
Thank you for flagging @vaidotasp. I missed this file when reviewing the code differences.

<img width="1406" alt="Screen Shot 2020-10-07 at 2 17 06 PM" src="https://user-images.githubusercontent.com/9040867/95371189-dae60380-08a7-11eb-959f-0cb274f9bdb8.png">

2020-10-13 11:13 UTC, vaidotasp approved these changes

2020-10-13 11:13 UTC, merged