setup banner alert message for trees in mosaic landscape
wri/gfw-mapbuilder pull request #1362
Opened 2023-08-16 16:23 UTC by davidlstarr

2023-08-21 19:45 UTC, anthonyamaro15 requested changes

2023-08-21 19:45 UTC, anthonyamaro15 commented on src/js/components/banner/Banner.tsx
> +  const selectedLanguage = useSelector((store: RootState) => store.appState.selectedLanguage);
This looks great @davidlstarr ! let's just remove the console logs

2023-08-23 13:52 UTC, davidlstarr commented
@anthonyamaro15 console logs have been removed and I added in `target='_blank'`.

2023-08-23 18:25 UTC, anthonyamaro15 approved these changes

2023-08-24 16:04 UTC, merged