Data Tab UI Implementation (pt 1)
wri/gfw-mapbuilder pull request #805
Opened 2020-02-19 18:23 UTC by vaidotasp

Part of #782
In Scope:
- Prev, Next button styling and functionality
- Layer selector styling and functionality
- Print Report button on the data panel

Out of Scope (and documented in #782)
- "X" button removes attribute from the map and data tab on click
- Active feature on map is highlighted and upon clicking NEXT/PREV highlighting changes to the next feature
- Table styling
- Language awareness

2020-02-19 21:53 UTC, SwampGuzzler commented on src/css/leftpanel.scss
> +  top: 140px;
`Change Request` ALERT!! No more `bottom` and we want `height` back in there somehow

2020-02-20 16:38 UTC, SwampGuzzler commented on src/js/components/leftPanel/dataPanel/DataTabFooter.tsx
> +        Print Report{' '}
Idk if we still need the `{' '}` now that our `.data-tabview-container .data-tabview-footer button img` has the proper `margin-left`

2020-02-20 16:39 UTC, SwampGuzzler commented on src/js/components/leftPanel/dataPanel/DataTabFooter.tsx
> +          src="https://my.gfw-mapbuilder.org/img/print-icon.svg"
@vaidotasp Let's eventually steal this `svg` and get it local in our code

2020-02-20 16:44 UTC, SwampGuzzler commented on src/js/components/leftPanel/dataPanel/DataTabView.tsx
> +      return null;
@vaidotasp Thoughts on whether this Component should be _ripped_ off of the DOM (and more importantly, have its local state of `3 of 14` or whatever be reset) when we have a different tab active (or no tab active), then come back to `1 of 14` every time that we switch tabs? This is Not a change request, let's look at this further down the line.

2020-02-20 16:45 UTC, SwampGuzzler commented on src/js/components/leftPanel/dataPanel/DataTabView.tsx
> +      return null;
Ooh let's also check this out again Once We Get The Highlights On The Map For The Selected Feature!

2020-02-20 17:10 UTC, SwampGuzzler requested changes
https://github.com/wri/gfw-mapbuilder/pull/805#discussion_r381567388 Style Changes and we are good!

2020-02-20 18:03 UTC, vaidotasp commented
yo @SwampGuzzler I think this is a better approach to control the height of the various tab views and their visibility https://github.com/wri/gfw-mapbuilder/pull/805/commits/7b971f83462e7153b073becd671ddeebb6613f57

2020-02-21 14:24 UTC, SwampGuzzler approved these changes
Looks good, as long as we remember to add the `tabview-container` class to all of our tabs Approved with `emphasis!`

2020-02-21 14:24 UTC, merged